[package]
name = "bevy-jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
bevy_asset_ron = "0.3.0"
serde = "1.0"
rand = "0.8.5"

[features]
default = ['bevy/dynamic']
